// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwHiJe1NigNgLb5jtrkTrjQlbYHjw1SIM',
    appId: '1:861107820797:web:3bb0abaa0a1d8e3b0e8694',
    messagingSenderId: '861107820797',
    projectId: 'vehiclesinfo-857e0',
    authDomain: 'vehiclesinfo-857e0.firebaseapp.com',
    storageBucket: 'vehiclesinfo-857e0.appspot.com',
    measurementId: 'G-ZY6HK3JR51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jLzgaOsBhi5oRZFjUVWQKD6Y80awMck',
    appId: '1:861107820797:android:e7517322a1e135d20e8694',
    messagingSenderId: '861107820797',
    projectId: 'vehiclesinfo-857e0',
    storageBucket: 'vehiclesinfo-857e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1PqwcIIUSA2PqECKJ_McFroJlk6kBEQ',
    appId: '1:861107820797:ios:bf2c72edbc39afb50e8694',
    messagingSenderId: '861107820797',
    projectId: 'vehiclesinfo-857e0',
    storageBucket: 'vehiclesinfo-857e0.appspot.com',
    androidClientId: '861107820797-52j3q3iahf22vij7r11o6ohvvvc3fian.apps.googleusercontent.com',
    iosClientId: '861107820797-ci2jh0hu2prdhvinlo2uhduchihi4qju.apps.googleusercontent.com',
    iosBundleId: 'com.mour.transferFilesAndVehiclesInfoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu1PqwcIIUSA2PqECKJ_McFroJlk6kBEQ',
    appId: '1:861107820797:ios:bf2c72edbc39afb50e8694',
    messagingSenderId: '861107820797',
    projectId: 'vehiclesinfo-857e0',
    storageBucket: 'vehiclesinfo-857e0.appspot.com',
    androidClientId: '861107820797-52j3q3iahf22vij7r11o6ohvvvc3fian.apps.googleusercontent.com',
    iosClientId: '861107820797-ci2jh0hu2prdhvinlo2uhduchihi4qju.apps.googleusercontent.com',
    iosBundleId: 'com.mour.transferFilesAndVehiclesInfoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwHiJe1NigNgLb5jtrkTrjQlbYHjw1SIM',
    appId: '1:861107820797:web:7e2387e70bbd36f20e8694',
    messagingSenderId: '861107820797',
    projectId: 'vehiclesinfo-857e0',
    authDomain: 'vehiclesinfo-857e0.firebaseapp.com',
    storageBucket: 'vehiclesinfo-857e0.appspot.com',
    measurementId: 'G-228TQ7GXC7',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDwHiJe1NigNgLb5jtrkTrjQlbYHjw1SIM',
    appId: '1:861107820797:web:e8616176c774cd680e8694',
    messagingSenderId: '861107820797',
    projectId: 'vehiclesinfo-857e0',
    authDomain: 'vehiclesinfo-857e0.firebaseapp.com',
    storageBucket: 'vehiclesinfo-857e0.appspot.com',
    measurementId: 'G-DZYRKWT65S',
  );
}
